import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("materials", "routes/materials.tsx"),
  route("customers", "routes/customers.tsx"),
  route("filaments", "routes/filaments.redirect.tsx"),
  route("clients", "routes/clients.redirect.tsx"),
  route("projects", "routes/projects._index.tsx"),
  route("projects/:id", "routes/projects.$id.tsx"),
  route("projects/:id/invoice", "routes/projects.$id.invoice.tsx"),
  route("quotes/*", "routes/quotes.redirect.tsx"),
  route("calculators", "routes/calculators._index.tsx"),
  route("calculators/:slug", "routes/calculators.$slug.tsx"),
  route("printers", "routes/printers._index.tsx"),
  route("printers/:slug", "routes/printers.$slug.tsx"),
  route("filament", "routes/filament._index.tsx"),
  route("filament/:slug", "routes/filament.$slug.tsx"),
  route("philippines", "routes/philippines.tsx"),
  route("guides", "routes/guides._index.tsx"),
  route("guides/:slug", "routes/guides.$slug.tsx"),
  route("c/:code", "routes/c.$code.tsx"),
  route("embed", "routes/embed.tsx"),
  route("embed/:section/:slug", "routes/embed.$section.$slug.tsx"),
  route("api/auth/*", "routes/api.auth.$.ts"),
  route("api/projects", "routes/api.projects.ts"),
  route("api/customers", "routes/api.customers.ts"),
  route("api/shares", "routes/api.shares.ts"),
  route("uploads/*", "routes/uploads.$.ts"),
  route("robots.txt", "routes/robots.txt.ts"),
  route("sitemap.xml", "routes/sitemap.xml.ts"),
] satisfies RouteConfig;
